language: php

php:
 - "5.4"
 - "5.5"
 - "5.6"
 - "7.0"

before_install:
# Set the GitHub OAuth token to make use of the 6000 per hour rate limit
 - mkdir -p ~/.composer
 - cp .travis.composer.json ~/.composer/config.json
# Update composer
 - composer self-update
# Install project
 - composer install --dev -o

before_script:
 - cd tests
 
script:
 - phpunit -d max_execution_time=0 
 - php ./coverage-checker.php ./clover.xml 100
