language: php

matrix:
  include:
  - php: '5.6'
  - php: '7.0'
    env:
    - EXECUTE_AFTER_SCRIPT=true

addons:
  apt:
    packages:
    - graphviz

env:
  global:
  - secure: eTtVtFTk5+jdkUUIa9HWWTprwvq5y+mxeQ3AbJc54AcKyTtPE7H9ywgsVCEp+n0z9t12bW5bgsCTMvFny1Vq/yYb1SIMUu37kCGohrGc2fgFIqanVHnetNTRjj4h5zZxll9GsaA5GEd4Pnn/LMbAGdO8AehDhbz7DIY6ZLuIA74=

sudo: false

cache:
  directories:
  - "$HOME/.composer/cache"

before_install:
- pear install phpdoc/phpDocumentor
- mkdir -p ~/.composer
- cp .travis.composer.json ~/.composer/config.json
- composer self-update
- composer install --prefer-dist --dev

before_script:
- mkdir -p build/{logs,coverage,phpdoc}

script:
- cd tests
- phpunit -d max_execution_time=0 --coverage-text --coverage-clover ../build/logs/clover.xml
  --coverage-html ../build/coverage/
- cd ..

after_script:
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then php vendor/bin/coveralls --verbose --config;fi
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then phpdoc -d "./src" -t "./build/phpdoc" --template="responsive-twig";fi
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then bash <(curl -s https://gist.githubusercontent.com/neilime/769d733c52acdecea8d2548fb3aca3ff/raw/853d54289f5c449ea9af6a4d8ca92e1f9fc80980/travis_ci_php_publish_build.sh);fi