<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Neilime\MobileDetect\Factory\MobileDetectFactory'              => __DIR__ . '/src/MobileDetect/factory/MobileDetectFactory.php',
    'Neilime\MobileDetect\Mvc\Controller\Plugin\MobileDetectPlugin' => __DIR__ . '/src/MobileDetect/Mvc/Controller/Plugin/MobileDetectPlugin.php',
    'Neilime\MobileDetect\View\Helper\MobileDetectHelper'           => __DIR__ . '/src/MobileDetect/View/Helper/MobileDetectHelper.php',
);
