<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Neilime\MobileDetect\Factory\MobileDetectFactory'                     => __DIR__ . '/src/MobileDetect/factory/MobileDetectFactory.php',
    'Neilime\MobileDetect\Mvc\Controller\Plugin\MobileDetectPlugin'        => __DIR__ . '/src/MobileDetect/Mvc/Controller/Plugin/MobileDetectPlugin.php',
    'Neilime\MobileDetect\Mvc\Controller\Plugin\MobileDetectPluginFactory' => __DIR__ . '/src/MobileDetect/Mvc/Controller/Plugin/MobileDetectPluginFactory.php',
    'Neilime\MobileDetect\View\Helper\MobileDetectHelper'                  => __DIR__ . '/src/MobileDetect/View/Helper/MobileDetectHelper.php',
    'Neilime\MobileDetect\View\Helper\MobileDetectHelperFactory'           => __DIR__ . '/src/MobileDetect/View/Helper/MobileDetectHelperFactory.php',
];
